// <auto-generated />
namespace Academico.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AcademicoInfraDataContextAcademicoContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AcademicoInfraDataContextAcademicoContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201607180059564_Academico.Infra.Data.Context.AcademicoContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
